In [9]:
df.to_csv("../dataset/processed_dataset.csv", index=False)

print("Processed dataset saved successfully!")

Processed dataset saved successfully!

In [8]:
label_map = {
    "Very Poor": 0,
    "Poor": 1,
    "Average": 2,
    "Good": 3,
    "Excellent": 4
}

df["label_encoded"] = df["label"].map(label_map)

df.head()

,question_id,subject,topic,difficulty,question,ideal_answer,student_answer,score,label,answer_length,label_encoded
0,PY001,Python,Basics,Easy,What is Python?,"Python is a high-level, interpreted, object-or...","Python is a high-level, interpreted, object-or...",10,Excellent,30,4
1,PY001,Python,Basics,Easy,What is Python?,"Python is a high-level, interpreted, object-or...","Technically, Python is a high-level, interpret...",8,Good,23,3
2,PY001,Python,Basics,Easy,What is Python?,"Python is a high-level, interpreted, object-or...","It can be defined as Python is a high-level, i...",6,Average,18,2
3,PY001,Python,Basics,Easy,What is Python?,"Python is a high-level, interpreted, object-or...",I have heard about it but don't remember.,3,Poor,8,1
4,PY001,Python,Basics,Easy,What is Python?,"Python is a high-level, interpreted, object-or...",I don't know.,2,Very Poor,3,0

In [7]:
df["answer_length"] = df["student_answer"].apply(lambda x: len(str(x).split()))

df.head()

,question_id,subject,topic,difficulty,question,ideal_answer,student_answer,score,label,answer_length
0,PY001,Python,Basics,Easy,What is Python?,"Python is a high-level, interpreted, object-or...","Python is a high-level, interpreted, object-or...",10,Excellent,30
1,PY001,Python,Basics,Easy,What is Python?,"Python is a high-level, interpreted, object-or...","Technically, Python is a high-level, interpret...",8,Good,23
2,PY001,Python,Basics,Easy,What is Python?,"Python is a high-level, interpreted, object-or...","It can be defined as Python is a high-level, i...",6,Average,18
3,PY001,Python,Basics,Easy,What is Python?,"Python is a high-level, interpreted, object-or...",I have heard about it but don't remember.,3,Poor,8
4,PY001,Python,Basics,Easy,What is Python?,"Python is a high-level, interpreted, object-or...",I don't know.,2,Very Poor,3

In [13]:
print("Duplicate rows:", df.duplicated().sum())

Duplicate rows: 0

In [14]:
print(df.shape)

(50, 9)

In [12]:
df.isnull().sum()

question_id       0
subject           0
topic             0
difficulty        0
question          0
ideal_answer      0
student_answer    0
score             0
label             0
dtype: int64

In [11]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   question_id     50 non-null     str
 1   subject         50 non-null     str
 2   topic           50 non-null     str
 3   difficulty      50 non-null     str
 4   question        50 non-null     str
 5   ideal_answer    50 non-null     str
 6   student_answer  50 non-null     str
 7   score           50 non-null     int64
 8   label           50 non-null     str
dtypes: int64(1), str(8)
memory usage: 3.6 KB

In [3]:
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

Rows: 50
Columns: 9

In [10]:
import pandas as pd

df = pd.read_csv("../dataset/dataset.csv")
df.head()

,question_id,subject,topic,difficulty,question,ideal_answer,student_answer,score,label
0,PY001,Python,Basics,Easy,What is Python?,"Python is a high-level, interpreted, object-or...","Python is a high-level, interpreted, object-or...",10,Excellent
1,PY001,Python,Basics,Easy,What is Python?,"Python is a high-level, interpreted, object-or...","Technically, Python is a high-level, interpret...",8,Good
2,PY001,Python,Basics,Easy,What is Python?,"Python is a high-level, interpreted, object-or...","It can be defined as Python is a high-level, i...",6,Average
3,PY001,Python,Basics,Easy,What is Python?,"Python is a high-level, interpreted, object-or...",I have heard about it but don't remember.,3,Poor
4,PY001,Python,Basics,Easy,What is Python?,"Python is a high-level, interpreted, object-or...",I don't know.,2,Very Poor